/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/indradhanush/debug-operator/pkg/apis/foo/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDebugLists implements DebugListInterface
type FakeDebugLists struct {
	Fake *FakeFooV1alpha1
}

var debuglistsResource = schema.GroupVersionResource{Group: "foo.example.com", Version: "v1alpha1", Resource: "debuglists"}

var debuglistsKind = schema.GroupVersionKind{Group: "foo.example.com", Version: "v1alpha1", Kind: "DebugList"}

// Get takes name of the debugList, and returns the corresponding debugList object, and an error if there is any.
func (c *FakeDebugLists) Get(name string, options v1.GetOptions) (result *v1alpha1.DebugList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(debuglistsResource, name), &v1alpha1.DebugList{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DebugList), err
}

// List takes label and field selectors, and returns the list of DebugLists that match those selectors.
func (c *FakeDebugLists) List(opts v1.ListOptions) (result *v1alpha1.DebugListList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(debuglistsResource, debuglistsKind, opts), &v1alpha1.DebugListList{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DebugListList), err
}

// Watch returns a watch.Interface that watches the requested debugLists.
func (c *FakeDebugLists) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(debuglistsResource, opts))
}

// Create takes the representation of a debugList and creates it.  Returns the server's representation of the debugList, and an error, if there is any.
func (c *FakeDebugLists) Create(debugList *v1alpha1.DebugList) (result *v1alpha1.DebugList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(debuglistsResource, debugList), &v1alpha1.DebugList{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DebugList), err
}

// Update takes the representation of a debugList and updates it. Returns the server's representation of the debugList, and an error, if there is any.
func (c *FakeDebugLists) Update(debugList *v1alpha1.DebugList) (result *v1alpha1.DebugList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(debuglistsResource, debugList), &v1alpha1.DebugList{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DebugList), err
}

// Delete takes name of the debugList and deletes it. Returns an error if one occurs.
func (c *FakeDebugLists) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(debuglistsResource, name), &v1alpha1.DebugList{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDebugLists) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(debuglistsResource, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.DebugListList{})
	return err
}

// Patch applies the patch and returns the patched debugList.
func (c *FakeDebugLists) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.DebugList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(debuglistsResource, name, data, subresources...), &v1alpha1.DebugList{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DebugList), err
}
