/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/indradhanush/debug-operator/pkg/apis/foo/v1alpha1"
	scheme "github.com/indradhanush/debug-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// DebugsGetter has a method to return a DebugInterface.
// A group's client should implement this interface.
type DebugsGetter interface {
	Debugs() DebugInterface
}

// DebugInterface has methods to work with Debug resources.
type DebugInterface interface {
	Create(*v1alpha1.Debug) (*v1alpha1.Debug, error)
	Update(*v1alpha1.Debug) (*v1alpha1.Debug, error)
	UpdateStatus(*v1alpha1.Debug) (*v1alpha1.Debug, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.Debug, error)
	List(opts v1.ListOptions) (*v1alpha1.DebugList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Debug, err error)
	DebugExpansion
}

// debugs implements DebugInterface
type debugs struct {
	client rest.Interface
}

// newDebugs returns a Debugs
func newDebugs(c *FooV1alpha1Client) *debugs {
	return &debugs{
		client: c.RESTClient(),
	}
}

// Get takes name of the debug, and returns the corresponding debug object, and an error if there is any.
func (c *debugs) Get(name string, options v1.GetOptions) (result *v1alpha1.Debug, err error) {
	result = &v1alpha1.Debug{}
	err = c.client.Get().
		Resource("debugs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Debugs that match those selectors.
func (c *debugs) List(opts v1.ListOptions) (result *v1alpha1.DebugList, err error) {
	result = &v1alpha1.DebugList{}
	err = c.client.Get().
		Resource("debugs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested debugs.
func (c *debugs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Resource("debugs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a debug and creates it.  Returns the server's representation of the debug, and an error, if there is any.
func (c *debugs) Create(debug *v1alpha1.Debug) (result *v1alpha1.Debug, err error) {
	result = &v1alpha1.Debug{}
	err = c.client.Post().
		Resource("debugs").
		Body(debug).
		Do().
		Into(result)
	return
}

// Update takes the representation of a debug and updates it. Returns the server's representation of the debug, and an error, if there is any.
func (c *debugs) Update(debug *v1alpha1.Debug) (result *v1alpha1.Debug, err error) {
	result = &v1alpha1.Debug{}
	err = c.client.Put().
		Resource("debugs").
		Name(debug.Name).
		Body(debug).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *debugs) UpdateStatus(debug *v1alpha1.Debug) (result *v1alpha1.Debug, err error) {
	result = &v1alpha1.Debug{}
	err = c.client.Put().
		Resource("debugs").
		Name(debug.Name).
		SubResource("status").
		Body(debug).
		Do().
		Into(result)
	return
}

// Delete takes name of the debug and deletes it. Returns an error if one occurs.
func (c *debugs) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("debugs").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *debugs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Resource("debugs").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched debug.
func (c *debugs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Debug, err error) {
	result = &v1alpha1.Debug{}
	err = c.client.Patch(pt).
		Resource("debugs").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
