/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	foo_v1alpha1 "github.com/indradhanush/debug-operator/pkg/apis/foo/v1alpha1"
	versioned "github.com/indradhanush/debug-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/indradhanush/debug-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/indradhanush/debug-operator/pkg/client/listers/foo/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// DebugInformer provides access to a shared informer and lister for
// Debugs.
type DebugInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.DebugLister
}

type debugInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewDebugInformer constructs a new informer for Debug type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDebugInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDebugInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredDebugInformer constructs a new informer for Debug type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDebugInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.FooV1alpha1().Debugs().List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.FooV1alpha1().Debugs().Watch(options)
			},
		},
		&foo_v1alpha1.Debug{},
		resyncPeriod,
		indexers,
	)
}

func (f *debugInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDebugInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *debugInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&foo_v1alpha1.Debug{}, f.defaultInformer)
}

func (f *debugInformer) Lister() v1alpha1.DebugLister {
	return v1alpha1.NewDebugLister(f.Informer().GetIndexer())
}
